# Form implementation generated from reading ui file 'pythonQT.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from ast import Lambda
import string
from PyQt6 import QtCore, QtGui, QtWidgets
import operator


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 345, 192))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")

        self.Button5 = QtWidgets.QPushButton(self.gridLayoutWidget, clicked = lambda: self.answer(MainWindow,"5"))
        self.Button5.setObjectName("Button5")
        self.gridLayout.addWidget(self.Button5, 1, 1, 1, 1)

        self.Button9 = QtWidgets.QPushButton(self.gridLayoutWidget, clicked = lambda: self.answer(MainWindow,"9"))
        self.Button9.setObjectName("Button9")
        self.gridLayout.addWidget(self.Button9, 2, 2, 1, 1)

        self.Button1 = QtWidgets.QPushButton(self.gridLayoutWidget, clicked = lambda: self.answer(MainWindow,"1"))
        self.Button1.setObjectName("Button1")
        self.gridLayout.addWidget(self.Button1, 0, 0, 1, 1)

        self.Multiply = QtWidgets.QPushButton(self.gridLayoutWidget, clicked = lambda: self.answer(MainWindow,"*"))
        self.Multiply.setObjectName("Multiply")
        self.gridLayout.addWidget(self.Multiply, 2, 3, 1, 1)

        self.Button4 = QtWidgets.QPushButton(self.gridLayoutWidget, clicked = lambda: self.answer(MainWindow,"4"))
        self.Button4.setObjectName("Button4")
        self.gridLayout.addWidget(self.Button4, 1, 0, 1, 1)

        self.Button0 = QtWidgets.QPushButton(self.gridLayoutWidget, clicked = lambda: self.answer(MainWindow,"0"))
        self.Button0.setObjectName("Button0")
        self.gridLayout.addWidget(self.Button0, 3, 0, 1, 1)

        self.Button7 = QtWidgets.QPushButton(self.gridLayoutWidget, clicked = lambda: self.answer(MainWindow,"7"))
        self.Button7.setObjectName("Button7")
        self.gridLayout.addWidget(self.Button7, 2, 0, 1, 1)

        self.Button8 = QtWidgets.QPushButton(self.gridLayoutWidget, clicked = lambda: self.answer(MainWindow,"8"))
        self.Button8.setObjectName("Button8")
        self.gridLayout.addWidget(self.Button8, 2, 1, 1, 1)

        self.Add = QtWidgets.QPushButton(self.gridLayoutWidget, clicked = lambda: self.answer(MainWindow,"+"))
        self.Add.setObjectName("Add")
        self.gridLayout.addWidget(self.Add, 0, 3, 1, 1)

        self.Button3 = QtWidgets.QPushButton(self.gridLayoutWidget, clicked = lambda: self.answer(MainWindow,"3"))
        self.Button3.setObjectName("Button3")
        self.gridLayout.addWidget(self.Button3, 0, 2, 1, 1)

        self.Button2 = QtWidgets.QPushButton(self.gridLayoutWidget, clicked = lambda: self.answer(MainWindow,"2"))
        self.Button2.setObjectName("Button2")
        self.gridLayout.addWidget(self.Button2, 0, 1, 1, 1)

        self.Button6 = QtWidgets.QPushButton(self.gridLayoutWidget, clicked = lambda: self.answer(MainWindow,"6"))
        self.Button6.setObjectName("Button6")
        self.gridLayout.addWidget(self.Button6, 1, 2, 1, 1)

        self.Subtract = QtWidgets.QPushButton(self.gridLayoutWidget, clicked = lambda: self.answer(MainWindow,"-"))
        self.Subtract.setObjectName("Subtract")
        self.gridLayout.addWidget(self.Subtract, 1, 3, 1, 1)

        self.Divide = QtWidgets.QPushButton(self.gridLayoutWidget, clicked = lambda: self.answer(MainWindow,"/"))
        self.Divide.setObjectName("Divide")
        self.gridLayout.addWidget(self.Divide, 3, 1, 1, 1)

        self.Equals = QtWidgets.QPushButton(self.gridLayoutWidget, clicked = lambda: self.answer(MainWindow,"="))
        self.Equals.setObjectName("Equals")
        self.gridLayout.addWidget(self.Equals, 3, 2, 1, 1)

        self.Result = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Result.setObjectName("Result")
        self.gridLayout.addWidget(self.Result, 4, 1, 1, 2)

        self.Backspace = QtWidgets.QPushButton(self.gridLayoutWidget, clicked = lambda: self.backspace(MainWindow))
        self.Backspace.setObjectName("Backspace")
        self.gridLayout.addWidget(self.Backspace, 5, 1, 1, 2)
        
        self.Clear = QtWidgets.QPushButton(self.gridLayoutWidget, clicked = lambda: self.clear(MainWindow))
        self.Clear.setObjectName("Clear")
        self.gridLayout.addWidget(self.Clear, 3, 3, 1, 1)
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    

    second_argument = ""
    operator = ""
    result = ""
    locked = False
    lastup = ""

    def answer(self, MainWindow, arg):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        if (arg == "1" or arg == "2" or arg == "3" or arg == "4" or arg == "5"  or 
        arg == "6"  or arg == "7"  or arg == "8"  or arg == "9" or arg == "0") and not self.locked and not self.operator:
            self.result += arg
            self.Result.setText(_translate("MainWindow", self.result))
            self.lastup = "first"

        elif arg == "+" or arg == "-" or arg == "*" or arg == "/" and not self.second_argument:
            self.operator = arg
            self.locked = True
            self.Result.setText(_translate("MainWindow", self.operator))
            self.lastup = "operator"

        elif self.operator and (arg == "1" or arg == "2" or 
        arg == "3" or arg == "4" or arg == "5"  or arg == "6"  or arg == "7"  or 
        arg == "8"  or arg == "9" or arg == "0"):
            self.second_argument += arg
            self.Result.setText(_translate("MainWindow", self.second_argument))
            self.lastup = "second"

        elif self.second_argument and arg == "=":
            self.result = str(eval (self.result+self.operator+self.second_argument))
            self.operator=""
            self.second_argument = ""
            self.lastup = ""
            self.Result.setText(_translate("MainWindow", self.result))

    def clear(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.result = self.operator = self.second_argument = ""
        self.Result.setText(_translate("MainWindow", ""))
        self.locked = False
    
    def backspace(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        if self.lastup == "first":
            self.result = self.result[:-1]
            self.Result.setText(_translate("MainWindow", self.result))
        if self.lastup == "operator":
            self.Result.setText(_translate("MainWindow", self.operator))
            self.operator = ""
        if self.lastup == "second":
            self.second_argument = self.second_argument[:-1]
            self.Result.setText(_translate("MainWindow", self.second_argument))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button5.setText(_translate("MainWindow", "5"))
        self.Button9.setText(_translate("MainWindow", "9"))
        self.Button1.setText(_translate("MainWindow", "1"))
        self.Multiply.setText(_translate("MainWindow", "x"))
        self.Button4.setText(_translate("MainWindow", "4"))
        self.Button0.setText(_translate("MainWindow", "0"))
        self.Button7.setText(_translate("MainWindow", "7"))
        self.Button8.setText(_translate("MainWindow", "8"))
        self.Add.setText(_translate("MainWindow", "+"))
        self.Button3.setText(_translate("MainWindow", "3"))
        self.Button2.setText(_translate("MainWindow", "2"))
        self.Button6.setText(_translate("MainWindow", "6"))
        self.Subtract.setText(_translate("MainWindow", "-"))
        self.Divide.setText(_translate("MainWindow", "/"))
        self.Equals.setText(_translate("MainWindow", "="))
        self.Result.setText(_translate("MainWindow", ""))
        self.Clear.setText(_translate("MainWindow", "Clear"))
        self.Backspace.setText(_translate("MainWindow", "Delete"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())


